#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import math
def quadratic(a, b, c):
	for x in (a,b,c):
        if not isinstance(x, (int, float)):
            raise TypeError('bad operand type')
    s=b**2-4*a*c
    if s>0 and a!=0:
        x1=(-b+math.sqrt(b**2-4*a*c))/(2*a)
        x2=(-b-math.sqrt(b**2-4*a*c))/(2*a)
        return (x1,x2)
    elif s==0 and a!=0:
        x=-b/2*a
        return x
    elif a==0 and b!=0:
        x=-c/b
        return x
    elif a==0 and b==0:
        return 'There are infinitely many solutions'
    else:
        return 'There is no solution'
